db='../data/sensordata.db'
dbTable='dhtreadings'
dbTable_sht_readings='shtreadings'
maxFailedSensorPings = 15
pin=27
sensor_am='AM2302'
sensor_sht='SHT-30'
sensor_sht_2='SHT-30 B'
irLightSensorPin=23
photoSensorPin=12
custom_i2c_sda=5
custom_i2c_scl=6
custom_i2c_bus=4
